DROP TABLE IF EXISTS TBL_USUARIOS;

CREATE TABLE TBL_USUARIOS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  nome VARCHAR(250) NOT NULL,
  senha VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  token VARCHAR(250) NOT NULL
);